name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.13
main: FactionsPro\FactionMain
api: [3.0.0]
softdepend: ["PureChat", "AntiSpamPro"]
extensions: [sqlite3]
